version: '3.9'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    depends_on:
      - db
    command: >
      sh -c "node scripts/seedUsers.js && node server.js"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
